# This file may be used to create an environment using:
# $ conda env create --name <env> --file <this file>
# platform: win-64
name: spotify-data-analysis
channels:
  - conda-forge
dependencies:
  - ipykernel
  - ipython
  - keras
  - conda-forge::keras-tuner
  - matplotlib
  - nbconvert
  - numpy
  - pandas
  - pillow
  - plotly
  - conda-forge::pydotplus
  - conda-forge::pygraphviz
  - python=3.10
  - scikit-learn
  - scipy
  - seaborn
  - statsmodels
  - tabulate
  - tensorflow